name: Add Skill Resource
description: Request to add a Skill Resource
body:
  - type: markdown
    attributes:
      value: |
        Before requesting to add a Skill Resource, please search for the Skill Resource in the existing issues. 
        
        ---
        
        Thank you for taking the time to request that we add a new Skill Resource, we really appreciate it! 
        
        To get the Skill Resource added as fast as possible, we need some information.
  - type: input
    id: name
    attributes:
      label: Name of the Skill Resource
      description: "What is the name of the Skill Resource you want to add?"
      placeholder: "e.g. Head First Python, 2nd Ed"
    validations:
      required: true
  - type: input
    id: skill_name
    attributes:
      label: Name of the Skill
      description: "For which Skill do you want to add this resource?"
      placeholder: "e.g. Python"
    validations:
      required: true
  - type: input
    id: weblink
    attributes:
      label: Link to the Skill Resource
      description: "Link to the Skill Resource"
      placeholder: "e.g. https://www.amazon.com/dp/1491919531"
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Skill Resource Category
      description: "Category that a particular Skill Resource falls into."
      options:
        - Online Course (e.g. Udemy, etc.)
        - Books
        - Website / Tutorial / Blog
        - Video (e.g. YouTube, etc.)
        - Official Docs
        - Something Else
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation why it should be added
      description: "Please provide us with a motivation why you think this would be a 
      great resource."
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Skill Resource Description
      description: "Brief description of the Skill Resource"
    validations:
      required: false
